### ISSUE TITLE
Add input/output examples

### ISSUE THREAD

**Issue by ai** [retyui/postcss-image-set-generator#1]
Thanks for new plugin :). I know how to make docs better.

Every PostCSS plugin [must](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md) have input/output example — it is the best to understand what plugin does.

**Comment by retyui** [comment]
Oh thanks !
Added : https://github.com/retyui/postcss-image-set-generator/commit/039b91b027fc97f509347c3c6c70588e25655d9b
